### ISSUE TITLE
Last step undo button?

### ISSUE THREAD

**Issue by ShreyasSkandan** [Trefo/agdss#26]
So I've been having a recurring problem during labelling and I think it might be worth addressing.

When i'm clicking and dragging around my labeler, I sometimes end up with a very small highlighted region (accidental). It's so small that I can't do the "double click to remove" operation. And I just end up having to refresh the page and I've sometimes lost a lot of labels doing this. I was wondering if adding a "undo last step" button was possible?

This is what I mean.
<img width="280" alt="screen shot 2016-08-15 at 6 03 27 pm" src="https://cloud.githubusercontent.com/assets/5595336/17681271/a894a7d6-6312-11e6-91ef-b732372cc855.png">

What do you guys think?

**Comment by darknight-007** [comment]
Ctrl + to zoom, and delete? Not at ALL user friendly, but there is a way. I think in general we need better zoom management.

**Comment by darknight-007** [comment]
Oh, and undo is a GREAT idea, I agree :)

**Comment by ShreyasSkandan** [comment]
I think in this particular case I could've zoomed in and fixed it but sometimes the highlighted region was too small to zoom and double click.

**Comment by dcunhas** [comment]
Would a list of all the labels (with the ability to delete them) be useful instead? I.e., a panel that lists each circle drawn. This could also be useful for multi-class labeling.
